### ISSUE TITLE
Decision Tree Classifier and Regressor

### ISSUE THREAD

**Issue by David2CN** [ches-001/MetaTune#1]

**Comment by David2CN** [comment]
how to handle parameters with multiple types? <br>
For example, ["min_samples_split"](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html) can be an integer or a float.

**Comment by gift-exe** [comment]
@ches-001 ... you might wanna see this ...

**Comment by gift-exe** [comment]
if we're going to be receiving the values from end users we might need to convert the values to the data type you prefer (maybe floats sha since it allows for more specific values).... I'm not sure sha

**Comment by David2CN** [comment]
the issue with this particular parameter is that the way it is used depends on the type. <br>
For example, ["min_samples_split"](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html):
    If int, then consider min_samples_split as the minimum number. <br>
    If float, then min_samples_split is a fraction and ceil(min_samples_split * n_samples) are the minimum number of samples for each split.

**Comment by gift-exe** [comment]
Ohh I understand... Is it possible to make provision for both the values? 🤔
Maybe if you can declare the parameter as:

`min_sample_split: Iterable[int, float] `

then in the method you can just check for the data type that was passed from the end user ... Something like this:

```
if isinstance(min_samples_split, float):
    #code for float value

If isinstance(min_samples_split, int):
    #code for int value

```
I'm not sure sha 🤧

**Comment by gift-exe** [comment]
I do have an issue
I've opened it

Could you please check it out
🤧

**Comment by ches-001** [comment]
@David2CN arguments that accept multiple types can be handled with ```trial.suggest_categorical``` or in this case ```trial.suggest_float``` is fine.

**Comment by ches-001** [comment]
@Gift-py I don't think there will be need to explicitly check types. but if you wish to annotate for multitypes, then use ```Union```

So, something like this: ```Iterable[Union[float, int]]```

**Comment by David2CN** [comment]
> Ohh I understand... Is it possible to make provision for both the values? 🤔 Maybe if you can declare the parameter as:
> 
> `min_sample_split: Iterable[int, float] `
> 
> then in the method you can just check for the data type that was passed from the end user ... Something like this:
> 
> ```
> if isinstance(min_samples_split, float):
>     #code for float value
> 
> If isinstance(min_samples_split, int):
>     #code for int value
> ```
> 
> I'm not sure sha 🤧

An issue with this is the the different types have different sample spaces:
the float type ranges from 0.0 to 1.0 and the int type goes from 1 to inf.

**Comment by David2CN** [comment]
I tried to work around it  this way:
```
int_or_float = trial.suggest_categorical("int_or_float", ["int", "float"])
        if int_or_float == "int":
            params["min_samples_split"] = trial.suggest_int("min_samples_split", *self.min_samples_split, log=False)
            params["min_samples_leaf"] = trial.suggest_int("min_samples_leaf", *self.min_samples_leaf, log=False)
        else:
            params["min_samples_split"] = trial.suggest_float("min_samples_split_floats", *self.min_samples_split_floats, log=False)
            params["min_samples_leaf"] = trial.suggest_float("min_samples_leaf_floats", *self.min_samples_leaf_floats, log=False)
```
so the search space for those variables would include both types.

**Comment by gift-exe** [comment]
> @Gift-py I don't think there will be need to explicitly check types. but if you wish to annotate for multitypes, then use ```Union```
> 
> So, something like this: ```Iterable[Union[float, int]]```

Nice nice

**Comment by gift-exe** [comment]
> I tried to work around it  this way:
> ```
> int_or_float = trial.suggest_categorical("int_or_float", ["int", "float"])
>         if int_or_float == "int":
>             params["min_samples_split"] = trial.suggest_int("min_samples_split", *self.min_samples_split, log=False)
>             params["min_samples_leaf"] = trial.suggest_int("min_samples_leaf", *self.min_samples_leaf, log=False)
>         else:
>             params["min_samples_split"] = trial.suggest_float("min_samples_split_floats", *self.min_samples_split_floats, log=False)
>             params["min_samples_leaf"] = trial.suggest_float("min_samples_leaf_floats", *self.min_samples_leaf_floats, log=False)
> ```
> so the search space for those variables would include both types.

This is cool ✨🤝🏾
