### ISSUE TITLE
Working On The Same File

### ISSUE THREAD

**Issue by gift-exe** [ches-001/MetaTune#3]
Are we supposed to create new files for each model? because we would end up having serious issues if we all try to merge after making changes on the same files... ( ie the tune_regressor/models.py and the tune_classifier/models.py )

@ches-001  : )

**Comment by ches-001** [comment]
Yes, that's right. I've changed the project structure. So you'll write each class into a new file.
Thank you

**Comment by gift-exe** [comment]
Aight ✨
